services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile

    depends_on:
      - mongo

    environment:
      - API_PORT=${API_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

    networks:
     - mongo-net

    ports:
      - ${API_PORT}:${API_PORT}

  mongo:
    image:
      mongo:latest

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - mongo-net

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

networks:
  mongo-net:
    driver: bridge
