version: '3'

services:
  api:
    build: .
    environment:
      PORT: 6969

    ports:
      - "6969:6969"

  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: 'db'
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"